testDjango/home/urls.py
from django.urls import path
from django.conf.urls import include
from . import views

urlpatterns = [
    path('', views.hello, name='hello')
]

testDjango/testProject/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from django.views.generic import RedirectView


urlpatterns = [
    path('admin/', admin.site.urls),
    path('home/', include('home.urls')),
    path('', RedirectView.as_view(url="/home/", permanent = True)), #  path에 공백을 넣으면 /home으로 리다이렉트되는 코드. :8000/입력도 :8000/home/ 페이지로 강제이동
    path('user/', include('user.urls')),
]

testDjango/user/urls.py
from django.urls import path
from . import views

app_name = 'user'
urlpatterns = [
    path('register/', views.register, name='register'),
]

testDjango/home/models.py
from django.db import models

# Create your models here.

testDjango/user/models.py
from django.db import models

class User(models.Model):
    user_id = models.CharField(max_length=32, unique=True, verbose_name='유저 아이디')
    user_pw = models.CharField(max_length=128, verbose_name='유저 비밀번호')
    user_name = models.CharField(max_length=16, unique=True, verbose_name='유저 이름')
    user_email = models.EmailField(max_length=128, unique=True, verbose_name='유저 이메일')
    user_register_dttm = models.DateTimeField(auto_now_add=True, verbose_name='계정 생성시간')
    
    def __str__(self):
        return self.user_name
    
    class Meta:
        db_table = 'user'
        verbose_name = '유저'
        verbose_name_plural = '유저'

testDjango/home/views.py
from django.shortcuts import render

def hello(request):
    return render(request, 'home/index.html')

testDjango/user/views.py
from django.shortcuts import render, redirect
from .models import User

def register(request):
    if request.method == 'GET':
        return render(request, 'user/register.html')
    
    elif request.method == 'POST':
        user_id = request.POST.get('id','')
        user_pw = request.POST.get('pw','')
        user_pw_confirm = request.POST.get('pw-confirm','')
        user_name = request.POST.get('name','')
        user_email = request.POST.get('email','')
        
        if(user_id or user_pw or user_pw_confirm or user_name or user_email) == '':
            return redirect('/user/register')
        elif user_pw != user_pw_confirm:
            return redirect('/user/register')
        else:
            user = User(
                user_id = user_id,
                user_pw = user_pw,
                user_name = user_name,
                user_email = user_email
            )
            user.save()
        return redirect('/')

testDjango/home/templates/home/index.html
<!DOCTYPE html>
<html lang="kr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>index</title>
</head>
<body>
    <h1>Django learn</h1>
    <a href="/"><button>홈으로</button></a>
    <a href=""><button>로그인</button></a>
    <a href="{% url 'user:register' %}"><button>회원가입</button></a>
    <div style = "border: 1px black solid; margin: 20px 0px;"></div>
    {% block contents %}
    {% endblock contents %}
</body>
</html>

testDjango/user/templates/user/register.html
{% extends 'home/index.html' %}

{% block contents %}
<div> 회원가입 페이지 </div>

<form action="" method="POST">
    {% csrf_token %}
    <div>
        <label for="id">아이디</label>
        <input type="text" id = "id" placeholder="아이디를 입력하세요." name="id">
    </div>
    <div>
        <label for="pw">비밀번호</label>
        <input type="password" id = "pw" placeholder="비밀번호를 입력하세요." name="pw">
    </div>
    <div>
        <label for="pw-confirm">비밀번호 확인</label>
        <input type="password" id = "pw-confirm" placeholder="비밀번호를 한 번 더 입력하세요." name="pw-confirm">
    </div>
    <div>
        <label for="name">이름</label>
        <input type="text" id = "name" placeholder=" 이름을 입력하세요." name="name">
    </div>
    <div>
        <label for="email">이메일</label>
        <input type="email" id = "email" placeholder="이메일을 입력하세요." name="email">
    </div>
    
    <button type="submit" name="register-submit" value="register">회원가입하기</button>

</form>
{% endblock contents %}